language: node_js
node_js:
  - "stable"

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - echo "test"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: build
  on:
    branch: master
