dist: focal  # Use Ubuntu 20.04 (Focal) for a newer glibc version
language: node_js
node_js:
  - "16"

branches:
  only:
    - main

cache:
  directories:
    - node_modules

install:
  - npm install


script:
  - yarn lint
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Make sure to set this token in Travis CI settings
  local_dir: build
  on:
    branch: main
