dist: focal  # Use Ubuntu 20.04 (Focal) for a newer glibc version
language: node_js
node_js:
  - "stable"

branches:
  only:
  - main

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "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"
  local_dir: build
  on:
    branch: main
